```{r Import Libraries and Data}
library(ggplot2)
library(mlr)

train <- read.csv("Treasury Recovery Act Data as of 9-30-2010.csv")
train
```

```{r Data Inspection}
columns<-colnames(train)
cat(columns, "\n\n\n")
summary(train)
```

```{r Column Metadata}
cat("Treasury Recovery Act Dataset for 2008\n")

cat("\nThis Dataset represents funds allocated by the United States Federal Governemnt in response to the Global Financial Crisis of 2008. Every Column represents funding given under a particular act or bond while every row represents funding given to a particular state. The last row also shows us the total funding given to all states in a particular Bond/Act.\n\n")

cat("\nThe details for each column are as below:\n")

cat("\n1. Recovery.Zone.Economic.Development.Bond.Allocation represents the funding given for econmic recovery through a refundable tax credit allowed under section 6431 of the Code equal to 45% of the interest payable by the issuer to investors.\n")

cat("\n2. The American Recovery and Reinvestment Tax Act of 2009 (the “Recovery Act”) created a new category of tax-exempt bonds called Recovery Zone Facility Bonds (“RZFBs”) to assist economic development in distressed areas throughout the United States.\n")

cat("\n3. Qualified school construction bonds allow schools to borrow at a nominal zero percent rate for the rehabilitation, repair and equipping of schools. In addition, QSCB funds can be used to purchase land on which a public school will be built. \n")

cat("\n4. Qualified Energy Conservation Bonds (QECBs) are federally subsidized bonds available to qualified states, local, and tribal issuers. A QECB is not a grant, but is among the lowest-cost public financing available for eligible energy efficiency, renewable energy, and mass commuting projects.\n")

cat("\n5. Qualified zone academic bonds allow certain qualified schools to borrow at nominal interest rates (as low as zero percent) for costs incurred in connection with the establishment of special programs in partnership with the private sector.\n")

cat("\n6. Tribal Economic Development Bonds are a new type of tax exempt borrowing created under the Stimulus Act passed by Congress in February 2009. Up to $2 billion in the aggregate may be issued by tribes nationwide\n")

cat("\n7. First Time Homebuyer Credit for Houses Purchased in  2009 - Number of Filers shows how many filers were there from each state\n")

cat("\n8. First Time Homebuyer Credit for Houses Purchased in 2009 - Sum of Credits Claimed shows the total credits claimed in each state\n")

cat("\n9. The Low-Income Housing Tax Credit provides a tax incentive to construct or rehabilitate affordable rental housing for low-income households.\n")

cat("\n10. Cash Assistance for Specified Energy Property is the assitance given by the treasury in lieu of investment tax credits to eligible applicants for specified energy property used in a trade or business or for the production of income.\n")

cat("\n11. New income tax credit provides an incentive for investment in low-income communities. The US Department of the Treasury competitively allocates tax credit authority to intermediaries that select investment projects.\n")

cat("\n12. Build America Bonds were debt securities issued by a state, municipality, or county to finance capital expenditures.\n")

```

```{r Data Cleaning}
toNumeric<-function(str){
  substring <- gsub("\\$","",str)
  substring <- gsub(",","",substring)
  return (as.numeric(substring))
}

for(x in 2:23){
  train[x] <- lapply(train[x], toNumeric)
}

print(train)
```

```{r Further Preprocessing}
row_sums <- c()

print(train[1,])

valid_columns <- c(2, 3, 4, 5, 6, 7, 9, 10, 11, 13, 15, 17, 19, 21)

for(x in 1:nrow(train)){
  sum <- 0
  for(y in valid_columns){
    sum <- sum + as.numeric(train[x,][y])
  }
  row_sums <- append(row_sums, sum)
}
train["Total.Allocation"] = row_sums

head(train,5)

```

```{r TODO: Visualisations}
ggplot(data = train[1:58,], aes(x = States, y = Total.Allocation)) + geom_point()+ theme(axis.text.x = element_text(hjust = 1, vjust=0.5, angle = 90)) + ggtitle("State Allocation")

x <- columns[valid_columns]
y <- as.numeric(train[60,])
y <- y[valid_columns]

barplot(y,names.arg=x,xlab="Month",ylab="Revenue",las=2, col="blue",
main="Revenue chart",border="black")
```

```{r Hypothesis Testing}
construction_data_2009 = as.numeric(train$X2009.Qualified.School.Construction.Bond.Allocation)
construction_data_2009 = construction_data_2009[1:56]

construction_data_2010 = as.numeric(train$X2010.Qualified.School.Construction.Bond.Allocation)
construction_data_2010 = construction_data_2010[1:56]

cat("We know that the mean for the Qualified School Construction bonds allocated in 2009 is", yellow(mean(construction_data_2009)))

cat("\n\nOur hypothesis is that the funds allocated for School Construction in 2010 would be less than that of 2009, as this fund was allocated i response to the 2008 financial crash, and after a whole year of recovery the need for funding should be reduced\n")

m = mean(construction_data_2010)
s = sd(construction_data_2010)
se = s/(sqrt(length(construction_data_2010)))
pvalue=pnorm(m,mean(construction_data_2009),se)

cat("\nAssuming a significance level of 5%, we can judge that")


if(pvalue<0.05) {
  cat(" our claim", green("cannot be rejected"), "\n")
} else {
  cat(" our claim can be", red("rejected"), "\n")
}

cat("\nHence, the mean for Funding allocated in 2010 is no less than that allocated in 2009")
```

```{r Viewing Principal Components}
library(factoextra)
train_numeric = data.frame(sapply(train, as.numeric))[1:58,]

train.pca = prcomp(train_numeric, scale = TRUE)
summary(train.pca)

cat("\n\n\nHence, We require only the first 6 Principal Components to represent ")
cat(green("92.939%"))
cat(" of the variance in the dataset.")

cat("\nWe also notice that most of the variance (")
cat(yellow("66.52"))
cat(") is defined by the first column.")

```

```{r PCA Visualisation}
#To visualise the data

fviz_eig(train.pca, main = "Percentage of Variance")

fviz_pca_var(train.pca, col.ind = "contrib", repel = TRUE,
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"))

```

```{r Correlation Testing}
library(crayon)

#First Test
cat("Correlation between Homebuying Credit Number of Filers and Total Credits Issued: ")
cat(green(cor(train_numeric$First.Time.Homebuyer.Credit.for.Houses.Purchased.in..2009...Number.of.Filers, train_numeric$First.Time.Homebuyer.Credit.for.Houses.Purchased.in.2009...Sum.of.Credits.Claimed)))
cat("\nClearly, the number of Filers and the sum of credits claimed for housing are highly correlated.\n\n")

#Second Test
cat("Next, we'll check the correlation between the Awards and Outlays for Low Income Housing Credits, which is: ")
cat(yellow(cor(train_numeric$Cash.Assistance.to.States.in.Lieu.of.Low.Income.Housing.Tax.Credit...Awards, train_numeric$Cash.Assistance.to.States.in.Lieu.of.Low.Income.Housing.Tax.Credit...Outlays)))
cat("\nAgain, the correlation between the two is there, but not as high.\n\n")

#Third Test
cat("Now, the correlation between Recovery Zone Development Bond Allocation and Tribal Bond Allocation: ")
cat(red(cor(train_numeric$Recovery.Zone.Economic.Development.Bond.Allocation, train_numeric$Tribal.Economic.Development.Bond.Allocation)))
cat("\nHere we see that the correlation between these is very low, suggesting that Tribal Zones have little to no effect on Recovery Zones.\n\n")

#Fourth Test
cat("Now, the correlation between Recovery Zone Development Bond Allocation and Facility Bond Allocation: ")
cat(green(cor(train_numeric$New.Markets.Tax.Credit....Number.of.Organizations, train_numeric$New.Markets.Tax.Credit...Awards)))
cat("\nThe correlation between the two is high.\n\n")

```

```{r Regression}

cat("For our regression example, we'll make a simple linear model to predict the total sum of First Time Homebuyer Credits given the number of Filers for it\n\n")

# Split into test and train

filers = as.numeric(train_numeric$First.Time.Homebuyer.Credit.for.Houses.Purchased.in..2009...Number.of.Filers)
filers = filers[filers != 0]

credits = as.numeric(train_numeric$First.Time.Homebuyer.Credit.for.Houses.Purchased.in.2009...Sum.of.Credits.Claimed)
credits = credits[credits != 0]

filers.train = filers[1:40]
filers.test = filers[41:50]

credits.train = credits[1:40]
credits.test = credits[41:50]

#Training and Evaluation
linear_model = lm(credits.train ~ filers.train)
lm.train = data.frame("Filers" = filers.train, "Credits"=credits.train)
print(ggplot(lm.train, aes(x=Filers,y=Credits))+geom_point() + geom_smooth(method = "lm", formula = y~x,col="red",se =F) + ggtitle("Filers Against Credits Issued"))

cat("The adjusted R Squared Value for the model is", green(summary(linear_model)$r.squared), "which shows that the model has adapted very well to the training data\n")

test = data.frame("filers.train" = filers.test)
predictions = predict(linear_model, test)
error = abs(credits.test - predictions)*100/credits.test

results = data.frame("Filers" = filers.test, "Credits"=credits.test, "Prediction"=predictions, "Error %"=error)
results

cat("\nThe model aslo works well with the test data, giving a mean absolute error of", yellow(mean(error)))
```

```{r Classification}

classification_data = data.frame("State" = train$States, "X2009 School Funds"=train$X2009.Qualified.School.Construction.Bond.Allocation, "X2010 School Funds" = train$X2010.Qualified.School.Construction.Bond.Allocation)
classification_data = classification_data[1:56,]

importance = (classification_data[,2] + classification_data[,3]) > mean(classification_data[,2] + classification_data[,3])
classification_data = cbind(classification_data, "Above Mean" = importance)
classification_data

```

